import type { AdminUpdateQuestion } from '@parel/validation/questionAdmin';
export declare function getQuestionById(id: string): Promise<{
    id: string;
    source: import(".prisma/client").$Enums.QuestionSource;
    metadata: import("@prisma/client/runtime/library").JsonValue | null;
    text: string;
    lang: import(".prisma/client").$Enums.Lang | null;
    visibility: import(".prisma/client").$Enums.ContentVisibility;
    createdAt: Date;
    localeCode: string | null;
    region: string | null;
    approved: boolean;
    categoryId: string;
    updatedAt: Date;
    ssscId: string;
    difficulty: string | null;
    currentVersionId: string | null;
    normalizedText: string | null;
    reviewNotes: string | null;
    createdByUserId: string | null;
    subCategoryId: string | null;
    subSubCategoryId: string | null;
    relatedToId: string | null;
    isLocalized: boolean;
    isFlagged: boolean;
    flagReason: string | null;
    reactionsLike: number;
    reactionsLaugh: number;
    reactionsThink: number;
} | null>;
export declare function listQuestionsByLeaf(opts: {
    ssscId: string;
    approved?: boolean;
    take?: number;
    skip?: number;
}): Promise<{
    id: string;
    source: import(".prisma/client").$Enums.QuestionSource;
    metadata: import("@prisma/client/runtime/library").JsonValue | null;
    text: string;
    lang: import(".prisma/client").$Enums.Lang | null;
    visibility: import(".prisma/client").$Enums.ContentVisibility;
    createdAt: Date;
    localeCode: string | null;
    region: string | null;
    approved: boolean;
    categoryId: string;
    updatedAt: Date;
    ssscId: string;
    difficulty: string | null;
    currentVersionId: string | null;
    normalizedText: string | null;
    reviewNotes: string | null;
    createdByUserId: string | null;
    subCategoryId: string | null;
    subSubCategoryId: string | null;
    relatedToId: string | null;
    isLocalized: boolean;
    isFlagged: boolean;
    flagReason: string | null;
    reactionsLike: number;
    reactionsLaugh: number;
    reactionsThink: number;
}[]>;
export declare function countQuestionsByLeaf(ssscId: string): Promise<{
    total: number;
    approved: number;
    unapproved: number;
}>;
export declare function adminUpdateQuestion(id: string, patch: AdminUpdateQuestion): Promise<{
    id: string;
    source: import(".prisma/client").$Enums.QuestionSource;
    metadata: import("@prisma/client/runtime/library").JsonValue | null;
    text: string;
    lang: import(".prisma/client").$Enums.Lang | null;
    visibility: import(".prisma/client").$Enums.ContentVisibility;
    createdAt: Date;
    localeCode: string | null;
    region: string | null;
    approved: boolean;
    categoryId: string;
    updatedAt: Date;
    ssscId: string;
    difficulty: string | null;
    currentVersionId: string | null;
    normalizedText: string | null;
    reviewNotes: string | null;
    createdByUserId: string | null;
    subCategoryId: string | null;
    subSubCategoryId: string | null;
    relatedToId: string | null;
    isLocalized: boolean;
    isFlagged: boolean;
    flagReason: string | null;
    reactionsLike: number;
    reactionsLaugh: number;
    reactionsThink: number;
}>;
export declare function bulkApproveQuestions(ids: string[]): Promise<{
    updated: number;
}>;
/**
 * Find likely duplicate questions by normalizedText in a given leaf
 */
export declare function findLikelyDuplicates(ssscId: string): Promise<Array<{
    normalizedText: string;
    ids: string[];
}>>;
export declare function getQuestionsBySsscId(ssscId: number): Promise<{
    id: string;
    source: import(".prisma/client").$Enums.QuestionSource;
    metadata: import("@prisma/client/runtime/library").JsonValue | null;
    text: string;
    lang: import(".prisma/client").$Enums.Lang | null;
    visibility: import(".prisma/client").$Enums.ContentVisibility;
    createdAt: Date;
    localeCode: string | null;
    region: string | null;
    approved: boolean;
    categoryId: string;
    updatedAt: Date;
    ssscId: string;
    difficulty: string | null;
    currentVersionId: string | null;
    normalizedText: string | null;
    reviewNotes: string | null;
    createdByUserId: string | null;
    subCategoryId: string | null;
    subSubCategoryId: string | null;
    relatedToId: string | null;
    isLocalized: boolean;
    isFlagged: boolean;
    flagReason: string | null;
    reactionsLike: number;
    reactionsLaugh: number;
    reactionsThink: number;
}[]>;
export declare function createQuestion(data: any): Promise<{
    id: string;
    source: import(".prisma/client").$Enums.QuestionSource;
    metadata: import("@prisma/client/runtime/library").JsonValue | null;
    text: string;
    lang: import(".prisma/client").$Enums.Lang | null;
    visibility: import(".prisma/client").$Enums.ContentVisibility;
    createdAt: Date;
    localeCode: string | null;
    region: string | null;
    approved: boolean;
    categoryId: string;
    updatedAt: Date;
    ssscId: string;
    difficulty: string | null;
    currentVersionId: string | null;
    normalizedText: string | null;
    reviewNotes: string | null;
    createdByUserId: string | null;
    subCategoryId: string | null;
    subSubCategoryId: string | null;
    relatedToId: string | null;
    isLocalized: boolean;
    isFlagged: boolean;
    flagReason: string | null;
    reactionsLike: number;
    reactionsLaugh: number;
    reactionsThink: number;
}>;
export declare function updateQuestion(data: any): Promise<{
    id: string;
    source: import(".prisma/client").$Enums.QuestionSource;
    metadata: import("@prisma/client/runtime/library").JsonValue | null;
    text: string;
    lang: import(".prisma/client").$Enums.Lang | null;
    visibility: import(".prisma/client").$Enums.ContentVisibility;
    createdAt: Date;
    localeCode: string | null;
    region: string | null;
    approved: boolean;
    categoryId: string;
    updatedAt: Date;
    ssscId: string;
    difficulty: string | null;
    currentVersionId: string | null;
    normalizedText: string | null;
    reviewNotes: string | null;
    createdByUserId: string | null;
    subCategoryId: string | null;
    subSubCategoryId: string | null;
    relatedToId: string | null;
    isLocalized: boolean;
    isFlagged: boolean;
    flagReason: string | null;
    reactionsLike: number;
    reactionsLaugh: number;
    reactionsThink: number;
}>;
export declare function deleteQuestion(id: string): Promise<{
    id: string;
    source: import(".prisma/client").$Enums.QuestionSource;
    metadata: import("@prisma/client/runtime/library").JsonValue | null;
    text: string;
    lang: import(".prisma/client").$Enums.Lang | null;
    visibility: import(".prisma/client").$Enums.ContentVisibility;
    createdAt: Date;
    localeCode: string | null;
    region: string | null;
    approved: boolean;
    categoryId: string;
    updatedAt: Date;
    ssscId: string;
    difficulty: string | null;
    currentVersionId: string | null;
    normalizedText: string | null;
    reviewNotes: string | null;
    createdByUserId: string | null;
    subCategoryId: string | null;
    subSubCategoryId: string | null;
    relatedToId: string | null;
    isLocalized: boolean;
    isFlagged: boolean;
    flagReason: string | null;
    reactionsLike: number;
    reactionsLaugh: number;
    reactionsThink: number;
}>;
