export declare function requireAdmin(): Promise<{
    id: string;
    role: import(".prisma/client").$Enums.UserRole;
    email: string;
    name: string | null;
}>;
export declare function requireAuth(): Promise<{
    id: string;
    image: string | null;
    role: import(".prisma/client").$Enums.UserRole;
    email: string;
    name: string | null;
    theme: string | null;
    lang: import(".prisma/client").$Enums.Lang;
    visibility: import(".prisma/client").$Enums.UserVisibility;
    username: string | null;
    xp: number;
    stats: import("@prisma/client/runtime/library").JsonValue | null;
    passwordHash: string | null;
    phone: string | null;
    language: string | null;
    country: string | null;
    dateOfBirth: Date | null;
    avatarUrl: string | null;
    bio: string | null;
    statusMessage: string | null;
    karma: number;
    avatarFrameId: string | null;
    isPublicProfile: boolean;
    banned: boolean;
    motto: string | null;
    funds: import("@prisma/client/runtime/library").Decimal;
    diamonds: number;
    level: number;
    lastLoginAt: Date | null;
    lastActiveAt: Date | null;
    createdAt: Date;
    streakCount: number;
    lastAnsweredAt: Date | null;
    score: number;
    questionsAnswered: number;
    questionsCreated: number;
    emailVerified: Date | null;
    emailVerifiedAt: Date | null;
    newsletterOptIn: boolean;
    archetype: string | null;
    archetypeKey: string | null;
    lastArchetypeReroll: Date | null;
    settings: import("@prisma/client/runtime/library").JsonValue | null;
    localeCode: string;
    ageGroup: string | null;
    region: string | null;
    interests: string[];
    tone: string | null;
    onboardingCompleted: boolean;
    combatKills: number;
    combatBattles: number;
    combatHighestStreak: number;
    statCreativity: number;
    statHealth: number;
    statKnowledge: number;
    statSleep: number;
    statSocial: number;
    allowPublicCompare: boolean;
    canBeAdded: string;
    badgeType: string | null;
    karmaScore: number;
    prestigeScore: number;
    showBadges: boolean;
    coins: number;
    seasonalXP: number;
    seasonLevel: number;
    seasonXP: number;
    prestigeCount: number;
    legacyPerk: string | null;
    prestigeTitle: string | null;
    prestigeBadgeId: string | null;
    prestigeColorTheme: string | null;
    currentGeneration: number;
    avatarTheme: string | null;
    moodFeed: string | null;
    equippedTitle: string | null;
    equippedIcon: string | null;
    equippedBackground: string | null;
}>;
