import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { safeAsync, unauthorizedError } from '@/lib/api-handler';
import { buildFunText, renderSvgCard } from '@/lib/comparison/cardText';

export const POST = safeAsync(async (req: NextRequest) => {
  const token = req.headers.get('x-cron-token');
  if (process.env.CRON_TOKEN && token !== process.env.CRON_TOKEN) {
    return unauthorizedError('Invalid token');
  }

  const now = new Date();
  const weekAgo = new Date(Date.now() - 7*24*60*60*1000);
  const users = await prisma.user.findMany({ select: { id: true, username: true, region: true }, take: 200 });

  let generated = 0;
  for (const u of users) {
    const myRefl = await prisma.userReflection.count({ where: { userId: u.id, createdAt: { gte: weekAgo } } });
    const totalUsers = await prisma.user.count();
    const totalRefl = await prisma.userReflection.count({ where: { createdAt: { gte: weekAgo } } });
    const globalAvg = totalUsers ? totalRefl / totalUsers : 0;
    const deltaPct = globalAvg ? ((myRefl - globalAvg) / globalAvg) * 100 : (myRefl > 0 ? 100 : 0);
    const stats = { metric: 'reflection rate', valuePct: Math.round(deltaPct) };
    const funText = buildFunText(u.username || 'You', (u as any).region || 'GLOBAL', stats);
    const bigNumber = `${Math.max(-99, Math.min(999, Math.round(deltaPct)))}%`;
    const svg = renderSvgCard(funText, bigNumber);
    const card = await prisma.comparisonCard.create({ data: { userId: u.id, statsJson: { myRefl, globalAvg, deltaPct }, funText, imageUrl: '/api/comparison-cards/share/TEMP', autoGenerated: true } });
    const imageUrl = `/api/comparison-cards/share/${card.id}`;
    await prisma.comparisonCard.update({ where: { id: card.id }, data: { imageUrl } });
    generated++;
  }

  return NextResponse.json({ success: true, generated });
});


