import type { ContentEntry } from "./contentTypes";
import { FLOW_CONTENT_KEYS } from "./flowContent";

export const CONTENT_REGISTRY: ContentEntry[] = [
  {
    key: FLOW_CONTENT_KEYS.insightHigh,
    type: "insight",
    value: "You think more like others than you expect.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.insightLow,
    type: "insight",
    value: "You see things differently than most people.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.insightNeutral,
    type: "insight",
    value: "You're somewhere between the average and the outliers.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.insightFallback,
    type: "insight",
    value: "You've completed your first comparison.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.insightHigh1,
    type: "insight",
    value: "You think more like others than you expect.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.insightHigh2,
    type: "insight",
    value: "Your answers line up with more people than you'd guess.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.insightLow1,
    type: "insight",
    value: "You see things differently than most people.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.insightLow2,
    type: "insight",
    value: "You consistently take a different lane from the crowd.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.insightMid1,
    type: "insight",
    value: "You're somewhere between the average and the outliers.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.insightMid2,
    type: "insight",
    value: "You balance common views with your own distinct takes.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.insightFallbackSubtitle,
    type: "text",
    value: "Keep going to see how your patterns compare with more people.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.insightAvgSubtitle,
    type: "text",
    value: "Average match right now:",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.archetypeAligned,
    type: "text",
    value: "The Aligned Thinker",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.archetypeOutlier,
    type: "text",
    value: "The Outlier",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.archetypeBalanced,
    type: "text",
    value: "The Balanced One",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.archetypeFallback,
    type: "text",
    value: "The Explorer",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.trustNote,
    type: "text",
    value: "Based on your answers in this flow. Early Alpha data may be limited.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.parallelsHeading,
    type: "text",
    value: "People like you",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.parallelsSubtitle,
    type: "text",
    value: "Based on your answers",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.parallelTitleVariant1,
    type: "text",
    value: "You and {name} think alike",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.parallelTitleVariant2,
    type: "text",
    value: "You and {name} see things similarly",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.parallelTitleVariant3,
    type: "text",
    value: "You and {name} often agree",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ctaTryAnotherFlow,
    type: "cta",
    value: "Try another flow",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ctaGoToDashboard,
    type: "cta",
    value: "Go to dashboard",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ctaCreateAccount,
    type: "cta",
    value: "Create account to save your results",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ctaCompareAnswers,
    type: "cta",
    value: "Compare answers",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.rewardLabel,
    type: "text",
    value: "You earned",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.rewardVariant1,
    type: "text",
    value: "You earned {amount}",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.rewardVariant2,
    type: "text",
    value: "{amount} added",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.rewardVariant3,
    type: "text",
    value: "Nice - {amount}",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.checkpointTitle,
    type: "checkpoint",
    value: "This is getting interesting.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.checkpointBody,
    type: "checkpoint",
    value: "Your answers are starting to form a pattern.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.checkpointProgressPrefix,
    type: "checkpoint",
    value: "About halfway through this topic",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.checkpointCuriosity,
    type: "checkpoint",
    value: "Next questions get more personal.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.checkpointKeepGoing,
    type: "cta",
    value: "Keep going",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.checkpointSwitchTopic,
    type: "cta",
    value: "Switch topic",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ambientFlowActivitySoft,
    type: "text",
    value: "People are answering this topic right now.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ambientFlowActivityCount,
    type: "text",
    value: "{count} people tried this topic",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ambientContinuationSoft,
    type: "text",
    value: "Many players continue after this point.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ambientCheckpointDeep,
    type: "text",
    value: "People usually slow down here.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ambientCheckpointFunny,
    type: "text",
    value: "This is where answers start getting weird.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ambientCheckpointSpicy,
    type: "text",
    value: "Most people hesitate before the next one.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ambientComparisonSoft,
    type: "text",
    value: "You are not answering in isolation.",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ambientComparisonCount,
    type: "text",
    value: "{count} answers already compare in this topic",
    active: true,
    priority: 1,
  },
  {
    key: FLOW_CONTENT_KEYS.ambientLighterNext,
    type: "text",
    value: "People often jump into a lighter flow next.",
    active: true,
    priority: 1,
  },
];

