ALTER TABLE "ops_runs" ADD COLUMN IF NOT EXISTS "entityType" TEXT;
ALTER TABLE "ops_runs" ADD COLUMN IF NOT EXISTS "entityId" TEXT;
ALTER TABLE "ops_runs" ADD COLUMN IF NOT EXISTS "entityLabel" TEXT;
ALTER TABLE "ops_runs" ADD COLUMN IF NOT EXISTS "params" JSONB;
ALTER TABLE "ops_runs" ADD COLUMN IF NOT EXISTS "warnings" JSONB;
ALTER TABLE "ops_runs" ADD COLUMN IF NOT EXISTS "errorStack" TEXT;
