import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/options';
import { prisma } from '@/lib/db';
import { safeAsync, unauthorizedError, validationError } from '@/lib/api-handler';
import { buildFunText, renderSvgCard } from '@/lib/comparison/cardText';

export const POST = safeAsync(async (req: NextRequest) => {
  const session = await getServerSession(authOptions);
  if (!session?.user?.email) return unauthorizedError('Unauthorized');

  const user = await prisma.user.findUnique({ where: { email: session.user.email }, select: { id: true, username: true, region: true, coins: true } as any });
  if (!user) return unauthorizedError('Unauthorized');

  // Charge small fee for manual trigger
  const fee = 10;
  if ((user as any).coins < fee) return validationError('Not enough coins');

  // Simple stats: compare user reflections count vs global avg
  const weekAgo = new Date(Date.now() - 7*24*60*60*1000);
  const myRefl = await prisma.userReflection.count({ where: { userId: user.id, createdAt: { gte: weekAgo } } });
  const totalUsers = await prisma.user.count();
  const totalRefl = await prisma.userReflection.count({ where: { createdAt: { gte: weekAgo } } });
  const globalAvg = totalUsers ? totalRefl / totalUsers : 0;
  const deltaPct = globalAvg ? ((myRefl - globalAvg) / globalAvg) * 100 : (myRefl > 0 ? 100 : 0);

  const stats = { metric: 'reflection rate', valuePct: Math.round(deltaPct) };
  const funText = buildFunText((user as any).username || 'You', (user as any).region || 'GLOBAL', stats);
  const bigNumber = `${Math.max(-99, Math.min(999, Math.round(deltaPct)))}%`;
  const svg = renderSvgCard(funText, bigNumber);

  // Image URL served via share endpoint
  const card = await prisma.$transaction(async (tx) => {
    await tx.user.update({ where: { id: user.id }, data: { coins: { decrement: fee } } });
    return await tx.comparisonCard.create({ data: {
      userId: user.id,
      statsJson: { myRefl, globalAvg },
      funText,
      imageUrl: `/api/comparison-cards/share/${'TEMP'}`,
      autoGenerated: false,
    }});
  });

  // Use id now
  const imageUrl = `/api/comparison-cards/share/${card.id}`;
  await prisma.comparisonCard.update({ where: { id: card.id }, data: { imageUrl } });

  return NextResponse.json({ success: true, card: { ...card, imageUrl, svg } });
});


